// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhOgBHKtAVTjmjLHyIYhXwftJXHVvuQk',
    appId: '1:33654827515:web:f6449c146af6559a8bc35e',
    messagingSenderId: '33654827515',
    projectId: 'fir-sample02-97c1f',
    authDomain: 'fir-sample02-97c1f.firebaseapp.com',
    storageBucket: 'fir-sample02-97c1f.appspot.com',
    measurementId: 'G-EJ5946EG7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hhKAEGvVfrl38-a8jI2XoKrwYs3m2M8',
    appId: '1:33654827515:android:5d0d59db9c8eecee8bc35e',
    messagingSenderId: '33654827515',
    projectId: 'fir-sample02-97c1f',
    storageBucket: 'fir-sample02-97c1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9TX-AmX-1deK3sUUAx0y1HKewQV-zqKE',
    appId: '1:33654827515:ios:b07e09f0ff4c2a1d8bc35e',
    messagingSenderId: '33654827515',
    projectId: 'fir-sample02-97c1f',
    storageBucket: 'fir-sample02-97c1f.appspot.com',
    iosClientId: '33654827515-2c6hi32jg29c3d4i2euq9ib2or4v7tn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9TX-AmX-1deK3sUUAx0y1HKewQV-zqKE',
    appId: '1:33654827515:ios:c2bab7e2389413638bc35e',
    messagingSenderId: '33654827515',
    projectId: 'fir-sample02-97c1f',
    storageBucket: 'fir-sample02-97c1f.appspot.com',
    iosClientId: '33654827515-mg1kuoah48b007q1mjkumen5dlvfhum2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample02.RunnerTests',
  );
}
